### ISSUE TITLE
Bug in *_available function: returns 0 if the buffer is full, halting communication

### ISSUE THREAD

**Issue by pramilo** [andygock/avr-uart#10]
Hi,

The issue is that, if the buffer gets full, the calculation that you have at *_available returns 0 for empty but also returns 0 if the buffer is full because of the formula used:

The formula is 
result = (UART_RX_BUFFER_MASK + UART_RxHead - UART_RxTail) % UART_RX_BUFFER_MASK

If RXHead = RXTail, it means RXHead-RxTail = 0, which in turn becomes: result = UART_RX_BUFFER_MASK % UART_RX_BUFFER_MASK which equals 0.

This means that any code relying on *available, when the buffer is full, will treat it as being empty and not pull any characters.

However the *putc functions can see the buffer is full and wll not receive any more data, efefctivelly making the UART stop working, without any notice.

A simpler way to rewrite available is:
result = (UART_RxHead != UART_RxTail);

I know that we are not supposed to come to a full buffer, but if we do, we should have a chance to understand it happened, as opposed to the UART mysteriously stopping to work.

This problem is particularly evident if you use high baud rates (250Kbps~500Kbps) and have a small buffer.

I would suggest implementing the change proposed on *available functions.

Thank you
Pedro.

**Comment by andygock** [comment]
@pramilo Thanks for that. I'll look into this soon.

**Comment by andygock** [comment]
@pramilo 

It's been a while since I looked at this code, but from what I can see:

`UART_RxHead` is never the same as `UART_RxTail` when the buffer is full. So it shouldn't be possible for example `uart0_available()` to return 0 when there is a full buffer. Do you agree?

Although it seems as the function is not returning the correct values anyway and not actually returning bytes available. Returning 0 or 1 perhaps is a better option in hindsight, however there may be people using the code who actually relies on it returning actual bytes available.

I was close to having a good implementation before commit 1dce1faeb18339256cd4042ccb3e1b99c1887afc but not sure why I changed it (it was a long time ago!)

Some reason it was

```
(UART_RX0_BUFFER_SIZE + UART_RxHead - UART_RxTail) & UART_RX0_BUFFER_MASK
```

When it would be better to have

```
(UART_RX0_BUFFER_MASK + UART_RxHead - UART_RxTail) % UART_RX0_BUFFER_MASK
```

**Comment by andygock** [comment]
From what I can tell, if buffer is full, head and tail pointers should not ever end up pointing to the same location anyway. Please correct me if I am mistaken?

I'm closing this, but will reopen if there is still a problem.
