### ISSUE TITLE
Reading string from uart

### ISSUE THREAD

**Issue by Aashutosh3804** [andygock/avr-uart#14]
How to read a string send over uart and store in array using getc method please help..
Not able to receive full string some bytes goes missing 
Please provide a simple code please

**Comment by ildar** [comment]
You mean you lose data while transferred through UART?

**Comment by Aashutosh3804** [comment]
Yes, while receiving I use uart0_getc() function to read until a 0 or \'r is in data and save in array but when I print array it stores sometimes multiple repeated string or sometimes missed characters 
Can you just provide a simple function to read a string send over uart and store in array until a null is receive I am unable to do so
You library is awesome it helped me a lot please help if possible

**Comment by Aashutosh3804** [comment]
> You mean you lose data while transferred through UART?

Yes, while receiving I use uart0_getc() function to read until a \0 or \r is in data and save in array but when I print array it stores sometimes multiple repeated string or sometimes missed characters
Can you just provide a simple function to read a string send over uart and store in array until a null is receive I am unable to do so
You library is awesome it helped me a lot please help if possible

**Comment by ildar** [comment]
Sorry, I'm not the author. But you may want to fix data loss problem which
is the root I believe.

**Comment by Aashutosh3804** [comment]
> Sorry, I'm not the author. But you may want to fix data loss problem which is the root I believe.

i used following code 

void uart0_readBytes(char * rxd){

  uint16_t rx;
  uint8_t rx_status, rx_data;
  int i = 0;
  while(1){
    rx = uart0_getc();
       rx_status = (uint8_t)(rx >> 8);
          rx = rx << 8;
         rx_data = (uint8_t)(rx >> 8);

         if ((rx_status == 0) && (rx_data != '\0') && (rx_data != '\r')) {

           rxd[i] = rx_data;
           i++;
        } else {
          break;
        }

     }

   }
int main(void) {

    uart0_init(UART_BAUD_SELECT(115200, F_CPU));
    uart0_flush();



    while(1){

        uart0_readBytes(rxd);

                uart0_puts(rxd); 



    }

    return 0;   
}
can you suggest some potential erros in my code

**Comment by ildar** [comment]
I suggest that UART data loss may originate from the HW problems

**Comment by Aashutosh3804** [comment]
Thanks for info I will try

**Comment by andygock** [comment]
@Aashutosh3804 

Unfortunately I don't have any samples, it's been a long time since I've used this or looked at the code, but quick look at your code.

- You should replace `\r` with `\0` before performing `uart0_puts(rxd)` otherwise you will end up transmitting the `\r` together with whatever chars are after it

- Are you losing data because your strings are longer than the size of the circular Rx buffer? Or you're receiving data (possibly multiple strings in succession) into the Rx buffer faster than the rate at you're able to transmit? Note that the `*puts()` functions will block your code if the Tx buffer is full.
